/*
 * bmimage.h - bitmap image loader via picture.datatype for FriendSh3ep.
 *
 * $VER: bmimage.h 1.0 (01.07.2026)
 * Copyright (C) 2026 FriendSh3ep contributors. All rights reserved.
 *
 * Loads JPEG/PNG/BMP/IFF images using datatypes.library v44+ and
 * picture.datatype, remapped to the current screen's bitmap format.
 *
 * Lifecycle:
 *   BmImage_Init()   -- once per instance, copies file path
 *   BmImage_Load()   -- on each screen open; sets bitmap pointer
 *   BmImage_Unload() -- on iconify / screen close; frees bitmap, keeps path
 *   BmImage_Free()   -- once at teardown; frees path too
 *
 * datatypes.library v44 is opened and closed via libraryTable in friendsh3ep.c.
 */

#ifndef BMIMAGE_H
#define BMIMAGE_H

#include <exec/types.h>
#include <intuition/intuition.h>
#include <graphics/gfx.h>
#include <intuition/classusr.h>

typedef enum {
    BMIMAGE_OK             = 0,
    BMIMAGE_ERR_NO_PATH,        /* NULL or empty path given to BmImage_Init */
    BMIMAGE_ERR_NO_MEMORY,      /* AllocVec failed */
    BMIMAGE_ERR_NO_DATATYPES,   /* datatypes.library v44 not available */
    BMIMAGE_ERR_OPEN_FAILED,    /* NewDTObject returned NULL */
    BMIMAGE_ERR_NO_BITMAP,      /* layout ok but no bitmap returned */
    BMIMAGE_ERR_WRITE_FAILED    /* couldn't write the scaled BMP thumbnail to disk */
} BmImageError;

/* Magic-byte-identified image format, independent of what datatypes
 * happen to be installed -- see BmImage_SniffFormat(). */
typedef enum {
    BMFMT_UNKNOWN = 0,
    BMFMT_PNG,
    BMFMT_JPEG,
    BMFMT_GIF,
    BMFMT_WEBP,
    BMFMT_BMP
} BmImageFormat;

typedef struct BmImage {
    char           *filePath;   /* AllocVec'd; survives Load/Unload cycles */
    Object         *dtObject;   /* picture.datatype object; NULL when unloaded */
    struct BitMap  *bitmap;     /* owned by dtObject; valid when dtObject != NULL */
    PLANEPTR        mask;       /* owned by dtObject; transparency mask generated by
                                  * the datatype from the source's transparent color
                                  * (e.g. palette index 0) or alpha channel -- see
                                  * PDTA_MaskPlane in datatypes/pictureclass.h.
                                  * NULL if the source has no transparency. */
    UWORD           width;      /* pixel width from BitMapHeader */
    UWORD           height;     /* pixel height from BitMapHeader */
    BmImageError    error;      /* last error code; BMIMAGE_OK on success */
} BmImage;

/*
 * Initialise from a file path.  Duplicates the path string.
 * Does NOT load the image — call BmImage_Load() to do that.
 * Returns FALSE if path is NULL/empty or AllocVec fails.
 */
BOOL BmImage_Init(BmImage *img, const char *path);

/*
 * Load (or reload) the bitmap, remapped to screen's depth and format.
 * Pass screen=NULL to load raw (un-remapped) source bitmap instead.
 * img->bitmap is valid after TRUE return; img->error is set after FALSE.
 * If already loaded, unloads the previous bitmap first.
 */
BOOL BmImage_Load(BmImage *img, struct Screen *screen);

/*
 * Load (or reload) the bitmap like BmImage_Load(), but scale it first.
 * Does not use picture.datatype's PDTM_SCALE (an earlier concern about it
 * having OS bugs turned out to be unfounded -- see BmImage_LoadFitScreen()
 * below, which does use it -- but this function still has its own reasons
 * to keep the BMP-roundtrip approach: arbitrary aspect-fit target sizes,
 * not just halving, and its own persistent-on-disk cache), nor a
 * source-less in-memory picture.datatype object (creating one doesn't work
 * on OS3). Instead, the scaled image is materialised as a BMP file next to
 * the source (same directory, named "<filePath>.<targetWidth>x<targetHeight>.bmp")
 * and loaded from disk like any other image -- see bmimage.c's file header
 * for the full pipeline. This works regardless of screen depth (truecolor
 * or paletted).
 *
 * That BMP thumbnail is a disk cache in its own right: if it already exists
 * from a previous call with the same targetWidth/targetHeight, it's loaded
 * directly with no decode/scale work at all. It lives alongside the source
 * file, so callers whose source path is itself inside a managed cache
 * directory (see network_fs3e/fs3enet_cache.h) get thumbnail cleanup for
 * free whenever that directory is flushed.
 *
 * targetWidth x targetHeight is treated like a bounding box: the source
 * rectangle is scaled (up or down) preserving its aspect ratio so it fits
 * entirely inside that box, touching either its left/right borders or its
 * top/bottom borders (whichever axis is the tighter fit) -- same rule
 * "avatar/attachment thumbnail" callers expect from a target-box fit.
 * img->width/height are the resulting scaled size, not targetWidth/Height.
 *
 * Pass screen=NULL to load raw (un-remapped); same lifecycle/ownership as
 * BmImage_Load() otherwise. Unlike BmImage_Load(), the resulting img->mask
 * is always NULL -- BMP has no alpha/transparent-colour channel.
 */
BOOL BmImage_LoadScaled(BmImage *img, struct Screen *screen,
                         UWORD targetWidth, UWORD targetHeight);

/*
 * Load (or reload) the bitmap like BmImage_Load(), except: if the source's
 * native pixel size is bigger than maxWidth x maxHeight in either
 * dimension, both dimensions are halved once via picture.datatype's
 * PDTM_SCALE before the image is ever decoded to a bitmap -- a single
 * halving, not a repeated fit-to-bounds loop, and not an aspect-preserving
 * box-fit to an arbitrary target size the way BmImage_LoadScaled() is.
 * This is the "don't let a huge attachment blow up past the screen" rule
 * fs3emediaview.c wants (maxWidth/maxHeight = CurrentMainScreen->Width/
 * Height minus a margin), which only ever needs one halving pass and gets
 * it essentially for free (PDTM_SCALE happens inside the same decode the
 * image needed anyway, no extra disk round-trip) -- unlike
 * BmImage_LoadScaled()'s BMP-roundtrip pipeline, built for a different job
 * (arbitrary small thumbnail box-fits with their own persistent cache).
 *
 * PDTM_SCALE must run before the object's first layout (see
 * picture_dtc.doc), so the native size is read from PDTA_BitMapHeader
 * before that happens here -- img->width/height end up reflecting
 * whatever the FINAL (possibly halved) size actually is, read back the
 * normal way after layout, same as BmImage_Load().
 *
 * maxWidth/maxHeight of 0 disables the check entirely (behaves exactly
 * like BmImage_Load()). Pass screen=NULL to load raw (un-remapped); same
 * lifecycle/ownership/mask handling as BmImage_Load() otherwise.
 */
BOOL BmImage_LoadFitScreen(BmImage *img, struct Screen *screen,
                            UWORD maxWidth, UWORD maxHeight);

/*
 * Screen-less half of the BmImage_LoadScaled pipeline: decode srcPath,
 * box-fit scale it to targetWidth x targetHeight (same pyramid-halve +
 * fixed-point nearest-neighbor pass, same aspect-fit rule), and write the
 * result to "<cacheKeyPath ? cacheKeyPath : srcPath>.<targetWidth>x
 * <targetHeight>.bmp" -- without the final reload-into-a-screen-bitmap
 * step, so it never touches Intuition. Safe to call from a screen-less
 * background task (see fs3ethumb.h's thumbnail process), which is the
 * only reason this is exposed separately from BmImage_LoadScaled (which
 * now calls this internally, passing cacheKeyPath=NULL, then opens the
 * result to a screen itself).
 *
 * cacheKeyPath decouples "where the thumbnail's deterministic name comes
 * from" from "where the source pixels are actually read from": pass NULL
 * to derive the sibling name from srcPath itself (the original, common
 * case -- source and thumbnail live side by side). Pass a non-NULL path
 * when srcPath is itself transient (e.g. a RAM:T download that gets
 * deleted right after this call) but the thumbnail still needs a stable
 * name persistent across runs -- see FS3EThumbMakeReq.fs3etmr_CacheKeyPath.
 * Either way this is purely a naming/cache-hit-check input, never opened
 * or read as a file itself.
 *
 * On a cache hit (thumbnail already on disk from a previous call with the
 * same cacheKeyPath/targetWidth/targetHeight), returns TRUE immediately
 * without decoding anything -- srcPath doesn't even need to still exist
 * in that case. outThumbPath is filled either way. Returns FALSE (with
 * outThumbPath untouched) on decode/scale/I-O failure; if outError is
 * non-NULL, it receives the BmImageError describing why.
 *
 * Requires DataTypesBase to already be open in the calling task's process
 * image -- true for the thumbnail process since it shares the GUI
 * executable's global data (see fs3ethumb.c).
 */
BOOL BmImage_GenerateScaledBmp(const char *srcPath, const char *cacheKeyPath,
                                UWORD targetWidth, UWORD targetHeight,
                                char *outThumbPath, ULONG outPathSize, BmImageError *outError);

/*
 * Screen-less, scale-less half of the BmImage_LoadScaled pipeline: opens
 * srcPath as a truecolor picture.datatype object and reads its pixels,
 * AT NATIVE SIZE, into a freshly AllocVec'd top-down RGB24 (3 bytes/pixel,
 * tightly packed rows, no padding) buffer -- exactly the format
 * RgbImage_LoadViaDatatype() (rgbimage.h) hands straight to an RgbImage,
 * and the same buffer shape BmImage_GenerateScaledBmp scales/writes as a
 * BMP. No scaling, no disk write: this is the "no minify" thumbnail path
 * (see fs3esettings.h's minifyThumbnails) -- a plain decode, nothing else.
 *
 * Caller FreeVec()s *outBuf. Returns FALSE (outBuf untouched) on failure;
 * if outError is non-NULL, receives the BmImageError describing why.
 */
BOOL BmImage_ReadSourceRgb(const char *srcPath, UBYTE **outBuf,
                            ULONG *outWidth, ULONG *outHeight,
                            BmImageError *outError);

/*
 * Read up to the first 16 bytes of path and identify its format from
 * magic bytes/signatures alone, independent of what datatypes happen to
 * be installed. Call this ONLY on a freshly downloaded source file that
 * NewDTObject already failed to open (BMIMAGE_ERR_OPEN_FAILED) -- e.g. to
 * tell a WebP image with no webp.datatype installed apart from a
 * corrupt/truncated download or a non-picture file. Never call this on
 * the app's own generated thumbnail BMPs -- RgbImage_LoadBmp doesn't go
 * through datatypes.library at all, so there's nothing to disambiguate
 * there. Returns BMFMT_UNKNOWN if the file can't be opened or matches no
 * known signature.
 */
BmImageFormat BmImage_SniffFormat(const char *path);

/*
 * Dispose the datatype object and clear bitmap/dimensions.
 * File path is kept so BmImage_Load() can be called again.
 * Call on iconify or screen close.
 */
void BmImage_Unload(BmImage *img);

/*
 * Unload bitmap and free the file path.  Leaves img zeroed.
 * Call once at final teardown.
 */
void BmImage_Free(BmImage *img);

/* TRUE once BmImage_Load() has succeeded and not been Unload()/Free()'d since. */
BOOL BmImage_IsLoaded(const BmImage *img);

#endif /* BMIMAGE_H */
